/* eslint-disable prettier/prettier */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_BY_ID = 'SET_USER_BY_ID';
export const SET_FORM = 'SET_FORM';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_TOKEN_FORGOT = 'SET_TOKEN_FORGOT';
export const SET_RECEIVING_ACCOUNT = 'SET_RECEIVING_ACCOUNT';
export const SET_DEPOSITS = 'SET_DEPOSITS';
export const SET_WITHDRAWS = 'SET_WITHDRAWS';
export const SET_CONTRACTS = 'SET_CONTRACTS';
export const SET_SEND_FUNDS = 'SET_SEND_FUNDS';
export const SET_DATA_DEPOSITS_HISTORY = 'SET_DATA_DEPOSITS_HISTORY';
export const SET_DATA_WITHDRAWS_HISTORY = 'SET_DATA_WITHDRAWS_HISTORY';
