export const SCREEN_NAVIGATE = {
  Home_Screen: 'Trang chủ',
  Login_Screen: 'Đăng nhập',
  Dashboard_Screen: 'Dashboard',
  NavPane_Screen: 'NavPane',
  Banner_Screen: 'Banner',
  Info_Screen: 'Thông tin',
  Setting_Screen: 'Cài đặt',
  Appearance_Screen: 'Giao diện',
  TimeKeeping_Screen: 'Chấm công',
  HR_Screen: 'Nhân sự',
  Marketing_Screen: 'Marketing',
  IT_Screen: 'IT',
  Calculator_Screen: 'Tính lương',
  Salary_Detail_Screen: 'Bảng lương chi tiết',
  Verify_TimeKeeping_Screnn: 'Duyệt bảng lương',
  Plan_Screen: 'Kế hoạch',
  Plan_Detail_Screen: 'Chi tiết kế hoạch',
  Bottom_Tab_Screen: 'MainPage',
  LoaderSliderCP_Screen: 'LoaderSliderCP',
};
