/* eslint-disable prettier/prettier */
import {
  ForgotPwd,
  Login,
  Register,
  ResetPwd,
  Deposits,
  Withdraw,
  Saving,
  Investment,
  InterestRate,
  Contract,
  Contact,
  ChangePhone,
  ReceivingAccount,
  ChangePwd,
  AffiliateAccount,
  TermsAndConditions,
  InviteFriends,
  CommissionsForInvestors,
  AikingOnWebsite,
  UserManual,
  QuestionAndAnswer,
  Hotline,
  UploadDeposits,
  VerifyWithdraw,
  Fund,
  Partner,
  CustomerCare,
  InterestRateTable,
  FundManagement,
  SendFunds,
  UploadDocument,
  UsdInvestmentFund,
  History,
  AgriculturalDevelopmentFund,
  ContractProvisions,
} from '../layouts';
import Routers from '../navigation/Routers';

export const routersMain = {
  Login: 'Login',
  Register: 'Register',
  ForgotPassword: 'ForgotPassword',
  ResetPwd: 'Reset Password',
  Deposits: 'Nạp tiền',
  Withdraw: 'Rút tiền',
  Saving: 'Gửi tiết kiệm',
  Investment: 'Đầu tư',
  Contract: 'Hợp đồng',
  InterestRate: 'Lãi suất',
  Contact: 'Liên hệ',
  ChangePhone: 'Thay đổi email',
  ReceivingAccount: 'Tài khoản nhận tiền',
  ChangePassword: 'Thay đổi mật khẩu',
  AffiliateAccount: 'Tài khoản liên kết',
  TermsAndConditions: 'Điều kiện và điều khoản',
  CommissionsForInvestors: 'Hoa hồng cho nhà đầu tư',
  InviteFriends: 'Mời bạn bè',
  AikingOnWebsite: 'Aiking.com',
  UserManual: 'Hướng dẫn sử dụng',
  QuestionAndAnswer: 'Hỏi đáp',
  Hotline: 'Hotline',
  Fund: 'Quỹ',
  Partner: 'Đối tác',
  CustomerCare: 'Chăm sóc khách hàng',
  InterestRateTable: 'Bảng lãi suất',
  FundManagement: 'Quản lý quỹ',
  SendFunds: 'Gửi quỹ',
  UsdInvestmentFund: 'Quỹ đầu tư USD',
  AgriculturalDevelopmentFund: 'Quỹ phát triển nông nghiệp',
  ContractProvisions: 'Các quy định hợp đồng',
  UploadDeposits: 'Tải hóa đơn nạp tiền',
  VerifyWithdraw: 'Xác thực rút tiền',
  UploadDocument: 'Giấy tờ',
  History: 'Lịch sử',
  MainPage: 'MainPage',
};
const MainObject = [
  {
    name: routersMain.Login,
    component: Login,
    options: 'headerNull',
  },
  {
    name: routersMain.Register,
    component: Register,
    options: 'headerNull',
  },
  {
    name: routersMain.ForgotPassword,
    component: ForgotPwd,
    options: 'headerNull',
  },
  {
    name: routersMain.ResetPwd,
    component: ResetPwd,
    options: 'headerNull',
  },
  {
    name: routersMain.Deposits,
    component: Deposits,
    options: 'custom',
  },
  {
    name: routersMain.Withdraw,
    component: Withdraw,
    options: 'custom',
  },
  {
    name: routersMain.Saving,
    component: Saving,
    options: 'custom',
  },
  {
    name: routersMain.Investment,
    component: Investment,
    options: 'custom',
  },
  {
    name: routersMain.Contract,
    component: Contract,
    options: 'custom',
  },
  {
    name: routersMain.InterestRate,
    component: InterestRate,
    options: 'custom',
  },
  {
    name: routersMain.Contact,
    component: Contact,
    options: 'custom',
  },
  {
    name: routersMain.ChangePhone,
    component: ChangePhone,
    options: 'custom',
  },
  {
    name: routersMain.ReceivingAccount,
    component: ReceivingAccount,
    options: 'custom',
  },
  {
    name: routersMain.ChangePassword,
    component: ChangePwd,
    options: 'custom',
  },
  {
    name: routersMain.AffiliateAccount,
    component: AffiliateAccount,
    options: 'custom',
  },
  {
    name: routersMain.TermsAndConditions,
    component: TermsAndConditions,
    options: 'custom',
  },
  {
    name: routersMain.InviteFriends,
    component: InviteFriends,
    options: 'custom',
  },
  {
    name: routersMain.CommissionsForInvestors,
    component: CommissionsForInvestors,
    options: 'custom',
  },
  {
    name: routersMain.AikingOnWebsite,
    component: AikingOnWebsite,
    options: 'custom',
  },
  {
    name: routersMain.UserManual,
    component: UserManual,
    options: 'custom',
  },
  {
    name: routersMain.QuestionAndAnswer,
    component: QuestionAndAnswer,
    options: 'custom',
  },
  {
    name: routersMain.Hotline,
    component: Hotline,
    options: 'custom',
  },
  {
    name: routersMain.UploadDeposits,
    component: UploadDeposits,
    options: 'custom',
  },
  {
    name: routersMain.VerifyWithdraw,
    component: VerifyWithdraw,
    options: 'custom',
  },
  {
    name: routersMain.Fund,
    component: Fund,
    options: 'custom',
  },
  {
    name: routersMain.Partner,
    component: Partner,
    options: 'custom',
  },
  {
    name: routersMain.CustomerCare,
    component: CustomerCare,
    options: 'custom',
  },
  {
    name: routersMain.InterestRateTable,
    component: InterestRateTable,
    options: 'custom',
  },
  {
    name: routersMain.FundManagement,
    component: FundManagement,
    options: 'custom',
  },
  {
    name: routersMain.SendFunds,
    component: SendFunds,
    options: 'custom',
  },
  {
    name: routersMain.UsdInvestmentFund,
    component: UsdInvestmentFund,
    options: 'custom',
  },
  {
    name: routersMain.AgriculturalDevelopmentFund,
    component: AgriculturalDevelopmentFund,
    options: 'custom',
  },
  {
    name: routersMain.ContractProvisions,
    component: ContractProvisions,
    options: 'custom',
  },
  {
    name: routersMain.UploadDocument,
    component: UploadDocument,
    options: 'custom',
  },
  {
    name: routersMain.History,
    component: History,
    options: 'custom',
  },
  {
    name: routersMain.MainPage,
    component: Routers,
  },
];

export default MainObject;
