const routers = {
	home: '/',
	signin: '/signin',
	singup: '/signup',
	forgorpwd: '/forgotPassword',
	verifyOtp: '/verifyOTP',
	aboutus: '/aboutus',
	training: '/training',
	developer: '/services/developer',
	investmentGold: '/services/investment-gold',
	servicesInvestment: '/services/services-investment',
	fundHome: '/services/fund/home',
	fundDeposits: '/services/fund/deposits',
	fundWithdraw: '/services/fund/withdraw',
	fundTransaction: '/services/fund/transaction',
	historyDepositWithdraw: '/services/fund/manager-deposits-withdraw',
	fundProfile: '/services/fund/profile',
	fund: '/services/fund',
	fundInterestRateTable: '/services/fund/interest-rate-table',
	fundManager: '/services/fund/manager-fund',
	fundSend: '/services/fund/send',
	fundCustomerCare: '/services/fund/customer-care',
	recruitment: '/recruitment',
	contact: '/contact',
	news: '/news',
};
export default routers;
