const routers = {
	home: '/',
	signin: '/signin',
	singup: '/signup',
	forgorpwd: '/forgotPassword',
	verifyOtp: '/verifyOTP',
	introduce: '/aboutus/introduce',
	financeReport: '/aboutus/financereport',
	training: '/training',
	web: '/productsandservices/web',
	servicesInvestment: '/productsandservices/services-investment',
	fundHome: '/productsandservices/fund/home',
	fundDeposits: '/productsandservices/fund/deposits',
	fundWithdraw: '/productsandservices/fund/withdraw',
	fundTransaction: '/productsandservices/fund/transaction',
	historyDepositWithdraw:
		'/productsandservices/fund/manager-deposits-withdraw',
	fundProfile: '/productsandservices/fund/profile',
	fund: '/productsandservices/fund',
	fundInterestRateTable: '/productsandservices/fund/interest-rate-table',
	fundManager: '/productsandservices/fund/manager-fund',
	fundSend: '/productsandservices/fund/send',
	fundCustomerCare: '/productsandservices/fund/customer-care',
	recruitment: '/recruitment',
	contact: '/contact',
};
export default routers;
